steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=gcloud.json.enc
      - --plaintext-file=gcloud.json
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./config/staging.secret.exs.enc
      - --plaintext-file=./config/staging.secret.exs
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/logflare-staging/logflare_origin:redis_$COMMIT_SHA",
        "-t",
        "gcr.io/logflare-staging/logflare_origin:redis_latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/logflare-staging/logflare_origin:redis_$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/logflare-staging/logflare_origin:redis_latest"]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - deployment/logflare-redis-staging
      - logflare=gcr.io/logflare-staging/logflare_origin:redis_$COMMIT_SHA
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1
      - CLOUDSDK_CONTAINER_CLUSTER=logflare-staging-redis-regional-cluster

timeout: 1800s

images:
  - gcr.io/logflare-staging/logflare_origin:redis_$COMMIT_SHA
