apiVersion: apps/v1
kind: Deployment
metadata:
  name: logflare-redis-staging
  labels:
    app: logflare-redis-staging
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  minReadySeconds: 30
  selector:
    matchLabels:
      app: logflare-redis-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logflare-redis-staging
    spec:
      containers:
        - image: gcr.io/logflare-staging/logflare_origin:redis_latest
          imagePullPolicy: Always
          name: logflare-redis-staging
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: RELEASE_COOKIE
              value: "temp_secret_cookie"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
